# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messuser', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=256)),
                ('pubtime', models.DateTimeField()),
            ],
        ),
    ]
